-- Found ament_cmake: 2.0.3 (/opt/ros/iron/share/ament_cmake/cmake)
-- Found ament_index_cpp: 1.5.2 (/opt/ros/iron/share/ament_index_cpp/cmake)
-- Found rosidl_default_generators: 1.5.0 (/opt/ros/iron/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
-- Found rosidl_adapter: 4.0.1 (/opt/ros/iron/share/rosidl_adapter/cmake)
-- Found std_msgs: 5.0.0 (/opt/ros/iron/share/std_msgs/cmake)
-- Found std_srvs: 5.0.0 (/opt/ros/iron/share/std_srvs/cmake)
[31mCMake Error at /opt/ros/iron/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  jibo_msgs --arguments-file
  /workspaces/jibo-workshop-fol2024/ros2_workspace/build/jibo_msgs/rosidl_adapter__arguments__jibo_msgs.json
  --output-dir
  /workspaces/jibo-workshop-fol2024/ros2_workspace/build/jibo_msgs/rosidl_adapter/jibo_msgs
  --output-file
  /workspaces/jibo-workshop-fol2024/ros2_workspace/build/jibo_msgs/rosidl_adapter/jibo_msgs.idls)
  returned error code 1:

  Error processing 'jibovec3 lookat' of 'jibo_msgs/JiboAction': ''jibovec3'
  is an invalid message name.  It should have the pattern
  '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 521, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 278, in __init__
      super(Type, self).__init__(
    File "/opt/ros/iron/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 206, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'jibovec3' is an invalid message
  name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /opt/ros/iron/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:25 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
See also "/workspaces/jibo-workshop-fol2024/ros2_workspace/build/jibo_msgs/CMakeFiles/CMakeOutput.log".
gmake: *** [Makefile:1895: cmake_check_build_system] Error 1
